### ISSUE TITLE
Run Error When Extracting Mesh

### ISSUE THREAD

**Issue by qianfanshen** [HLinChen/VCR-GauS#8]
Thank you for excellent work, when extracting mesh on the truck scene in TNT dataset using the default command `python python_scripts/run_tnt.py`, I encountered OOM, while my device is A100 with 40GB memory. However, when I tried to modify some parameters like increase the voxel_size, there was kernel error as below.
<img width="1077" alt="error" src="https://github.com/user-attachments/assets/4140ac84-5fef-48a8-96b3-ffc03eefa2dc">
@HLinChen

**Comment by HLinChen** [comment]
In this [line](https://github.com/HLinChen/VCR-GauS/blob/4fc132c285c6fb405c526fe83ec83fbb8a30f2fc/python_scripts/run_tnt.py#L47C1-L47C79), I set many voxel_size. And find the smallest voxel_size by traversing this list.

**Comment by qianfanshen** [comment]
Thanks a lot, it has been solved now. Another problem is that how can i get the background mesh or in other words, the mesh of the whole scene?

**Comment by HLinChen** [comment]
I use a bounding box to build an object and remove the background. If you want to get the background mesh, you can comment this [line](https://github.com/HLinChen/VCR-GauS/blob/4fc132c285c6fb405c526fe83ec83fbb8a30f2fc/tools/depth2mesh.py#L144).

**Comment by ianpark318** [comment]
Hi, how did you set the voxel size?
In my case, even I set voxel_size as [20.0, 15.0, 10.0], still can't solve the OOM issue.
Could you let me know the voxel_size you set?

Thanks!
